version: 0.1

phases:

  install:
    commands:
      - go get -u ./...

  pre_build:
    commands:
      - go test ./...

  build:
    commands:
      - go build -o app main.go

artifacts:
  files:
    - app
    - appspec.yml
    - buildspec.yml
    - codedeploy/*
