// Code generated by SQLBoiler 4.11.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/volatiletech/randomize"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testSourceReferences(t *testing.T) {
	t.Parallel()

	query := SourceReferences()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testSourceReferencesDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSourceReferencesQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := SourceReferences().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSourceReferencesSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SourceReferenceSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testSourceReferencesExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := SourceReferenceExists(ctx, tx, o.Value)
	if err != nil {
		t.Errorf("Unable to check if SourceReference exists: %s", err)
	}
	if !e {
		t.Errorf("Expected SourceReferenceExists to return true, but got false.")
	}
}

func testSourceReferencesFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	sourceReferenceFound, err := FindSourceReference(ctx, tx, o.Value)
	if err != nil {
		t.Error(err)
	}

	if sourceReferenceFound == nil {
		t.Error("want a record, got nil")
	}
}

func testSourceReferencesBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = SourceReferences().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testSourceReferencesOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := SourceReferences().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testSourceReferencesAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	sourceReferenceOne := &SourceReference{}
	sourceReferenceTwo := &SourceReference{}
	if err = randomize.Struct(seed, sourceReferenceOne, sourceReferenceDBTypes, false, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}
	if err = randomize.Struct(seed, sourceReferenceTwo, sourceReferenceDBTypes, false, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sourceReferenceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sourceReferenceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SourceReferences().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testSourceReferencesCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	sourceReferenceOne := &SourceReference{}
	sourceReferenceTwo := &SourceReference{}
	if err = randomize.Struct(seed, sourceReferenceOne, sourceReferenceDBTypes, false, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}
	if err = randomize.Struct(seed, sourceReferenceTwo, sourceReferenceDBTypes, false, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = sourceReferenceOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = sourceReferenceTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func sourceReferenceBeforeInsertHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceAfterInsertHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceAfterSelectHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceBeforeUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceAfterUpdateHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceBeforeDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceAfterDeleteHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceBeforeUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func sourceReferenceAfterUpsertHook(ctx context.Context, e boil.ContextExecutor, o *SourceReference) error {
	*o = SourceReference{}
	return nil
}

func testSourceReferencesHooks(t *testing.T) {
	t.Parallel()

	var err error

	ctx := context.Background()
	empty := &SourceReference{}
	o := &SourceReference{}

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, false); err != nil {
		t.Errorf("Unable to randomize SourceReference object: %s", err)
	}

	AddSourceReferenceHook(boil.BeforeInsertHook, sourceReferenceBeforeInsertHook)
	if err = o.doBeforeInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeInsertHook function to empty object, but got: %#v", o)
	}
	sourceReferenceBeforeInsertHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.AfterInsertHook, sourceReferenceAfterInsertHook)
	if err = o.doAfterInsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterInsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterInsertHook function to empty object, but got: %#v", o)
	}
	sourceReferenceAfterInsertHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.AfterSelectHook, sourceReferenceAfterSelectHook)
	if err = o.doAfterSelectHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterSelectHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterSelectHook function to empty object, but got: %#v", o)
	}
	sourceReferenceAfterSelectHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.BeforeUpdateHook, sourceReferenceBeforeUpdateHook)
	if err = o.doBeforeUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpdateHook function to empty object, but got: %#v", o)
	}
	sourceReferenceBeforeUpdateHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.AfterUpdateHook, sourceReferenceAfterUpdateHook)
	if err = o.doAfterUpdateHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpdateHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpdateHook function to empty object, but got: %#v", o)
	}
	sourceReferenceAfterUpdateHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.BeforeDeleteHook, sourceReferenceBeforeDeleteHook)
	if err = o.doBeforeDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeDeleteHook function to empty object, but got: %#v", o)
	}
	sourceReferenceBeforeDeleteHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.AfterDeleteHook, sourceReferenceAfterDeleteHook)
	if err = o.doAfterDeleteHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterDeleteHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterDeleteHook function to empty object, but got: %#v", o)
	}
	sourceReferenceAfterDeleteHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.BeforeUpsertHook, sourceReferenceBeforeUpsertHook)
	if err = o.doBeforeUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doBeforeUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected BeforeUpsertHook function to empty object, but got: %#v", o)
	}
	sourceReferenceBeforeUpsertHooks = []SourceReferenceHook{}

	AddSourceReferenceHook(boil.AfterUpsertHook, sourceReferenceAfterUpsertHook)
	if err = o.doAfterUpsertHooks(ctx, nil); err != nil {
		t.Errorf("Unable to execute doAfterUpsertHooks: %s", err)
	}
	if !reflect.DeepEqual(o, empty) {
		t.Errorf("Expected AfterUpsertHook function to empty object, but got: %#v", o)
	}
	sourceReferenceAfterUpsertHooks = []SourceReferenceHook{}
}

func testSourceReferencesInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSourceReferencesInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(sourceReferenceColumnsWithoutDefault...)); err != nil {
		t.Error(err)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testSourceReferenceToManySourceTokenPrices(t *testing.T) {
	var err error
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SourceReference
	var b, c TokenPrice

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	if err = randomize.Struct(seed, &b, tokenPriceDBTypes, false, tokenPriceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tokenPriceDBTypes, false, tokenPriceColumnsWithDefault...); err != nil {
		t.Fatal(err)
	}

	queries.Assign(&b.Source, a.Value)
	queries.Assign(&c.Source, a.Value)
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := a.SourceTokenPrices().All(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	bFound, cFound := false, false
	for _, v := range check {
		if queries.Equal(v.Source, b.Source) {
			bFound = true
		}
		if queries.Equal(v.Source, c.Source) {
			cFound = true
		}
	}

	if !bFound {
		t.Error("expected to find b")
	}
	if !cFound {
		t.Error("expected to find c")
	}

	slice := SourceReferenceSlice{&a}
	if err = a.L.LoadSourceTokenPrices(ctx, tx, false, (*[]*SourceReference)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SourceTokenPrices); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	a.R.SourceTokenPrices = nil
	if err = a.L.LoadSourceTokenPrices(ctx, tx, true, &a, nil); err != nil {
		t.Fatal(err)
	}
	if got := len(a.R.SourceTokenPrices); got != 2 {
		t.Error("number of eager loaded records wrong, got:", got)
	}

	if t.Failed() {
		t.Logf("%#v", check)
	}
}

func testSourceReferenceToManyAddOpSourceTokenPrices(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SourceReference
	var b, c, d, e TokenPrice

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sourceReferenceDBTypes, false, strmangle.SetComplement(sourceReferencePrimaryKeyColumns, sourceReferenceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*TokenPrice{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tokenPriceDBTypes, false, strmangle.SetComplement(tokenPricePrimaryKeyColumns, tokenPriceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	foreignersSplitByInsertion := [][]*TokenPrice{
		{&b, &c},
		{&d, &e},
	}

	for i, x := range foreignersSplitByInsertion {
		err = a.AddSourceTokenPrices(ctx, tx, i != 0, x...)
		if err != nil {
			t.Fatal(err)
		}

		first := x[0]
		second := x[1]

		if !queries.Equal(a.Value, first.Source) {
			t.Error("foreign key was wrong value", a.Value, first.Source)
		}
		if !queries.Equal(a.Value, second.Source) {
			t.Error("foreign key was wrong value", a.Value, second.Source)
		}

		if first.R.SourceSourceReference != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}
		if second.R.SourceSourceReference != &a {
			t.Error("relationship was not added properly to the foreign slice")
		}

		if a.R.SourceTokenPrices[i*2] != first {
			t.Error("relationship struct slice not set to correct value")
		}
		if a.R.SourceTokenPrices[i*2+1] != second {
			t.Error("relationship struct slice not set to correct value")
		}

		count, err := a.SourceTokenPrices().Count(ctx, tx)
		if err != nil {
			t.Fatal(err)
		}
		if want := int64((i + 1) * 2); count != want {
			t.Error("want", want, "got", count)
		}
	}
}

func testSourceReferenceToManySetOpSourceTokenPrices(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SourceReference
	var b, c, d, e TokenPrice

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sourceReferenceDBTypes, false, strmangle.SetComplement(sourceReferencePrimaryKeyColumns, sourceReferenceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*TokenPrice{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tokenPriceDBTypes, false, strmangle.SetComplement(tokenPricePrimaryKeyColumns, tokenPriceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err = a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = c.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.SetSourceTokenPrices(ctx, tx, false, &b, &c)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.SourceTokenPrices().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	err = a.SetSourceTokenPrices(ctx, tx, true, &d, &e)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.SourceTokenPrices().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Source) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Source) {
		t.Error("want c's foreign key value to be nil")
	}
	if !queries.Equal(a.Value, d.Source) {
		t.Error("foreign key was wrong value", a.Value, d.Source)
	}
	if !queries.Equal(a.Value, e.Source) {
		t.Error("foreign key was wrong value", a.Value, e.Source)
	}

	if b.R.SourceSourceReference != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.SourceSourceReference != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.SourceSourceReference != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}
	if e.R.SourceSourceReference != &a {
		t.Error("relationship was not added properly to the foreign struct")
	}

	if a.R.SourceTokenPrices[0] != &d {
		t.Error("relationship struct slice not set to correct value")
	}
	if a.R.SourceTokenPrices[1] != &e {
		t.Error("relationship struct slice not set to correct value")
	}
}

func testSourceReferenceToManyRemoveOpSourceTokenPrices(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a SourceReference
	var b, c, d, e TokenPrice

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, sourceReferenceDBTypes, false, strmangle.SetComplement(sourceReferencePrimaryKeyColumns, sourceReferenceColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	foreigners := []*TokenPrice{&b, &c, &d, &e}
	for _, x := range foreigners {
		if err = randomize.Struct(seed, x, tokenPriceDBTypes, false, strmangle.SetComplement(tokenPricePrimaryKeyColumns, tokenPriceColumnsWithoutDefault)...); err != nil {
			t.Fatal(err)
		}
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	err = a.AddSourceTokenPrices(ctx, tx, true, foreigners...)
	if err != nil {
		t.Fatal(err)
	}

	count, err := a.SourceTokenPrices().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 4 {
		t.Error("count was wrong:", count)
	}

	err = a.RemoveSourceTokenPrices(ctx, tx, foreigners[:2]...)
	if err != nil {
		t.Fatal(err)
	}

	count, err = a.SourceTokenPrices().Count(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}
	if count != 2 {
		t.Error("count was wrong:", count)
	}

	if !queries.IsValuerNil(b.Source) {
		t.Error("want b's foreign key value to be nil")
	}
	if !queries.IsValuerNil(c.Source) {
		t.Error("want c's foreign key value to be nil")
	}

	if b.R.SourceSourceReference != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if c.R.SourceSourceReference != nil {
		t.Error("relationship was not removed properly from the foreign struct")
	}
	if d.R.SourceSourceReference != &a {
		t.Error("relationship to a should have been preserved")
	}
	if e.R.SourceSourceReference != &a {
		t.Error("relationship to a should have been preserved")
	}

	if len(a.R.SourceTokenPrices) != 2 {
		t.Error("should have preserved two relationships")
	}

	// Removal doesn't do a stable deletion for performance so we have to flip the order
	if a.R.SourceTokenPrices[1] != &d {
		t.Error("relationship to d should have been preserved")
	}
	if a.R.SourceTokenPrices[0] != &e {
		t.Error("relationship to e should have been preserved")
	}
}

func testSourceReferencesReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSourceReferencesReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := SourceReferenceSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testSourceReferencesSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := SourceReferences().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	sourceReferenceDBTypes = map[string]string{`Value`: `character varying`}
	_                      = bytes.MinRead
)

func testSourceReferencesUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(sourceReferencePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(sourceReferenceAllColumns) == len(sourceReferencePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferencePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testSourceReferencesSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(sourceReferenceAllColumns) == len(sourceReferencePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &SourceReference{}
	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferenceColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, sourceReferenceDBTypes, true, sourceReferencePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(sourceReferenceAllColumns, sourceReferencePrimaryKeyColumns) {
		fields = sourceReferenceAllColumns
	} else {
		fields = strmangle.SetComplement(
			sourceReferenceAllColumns,
			sourceReferencePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := SourceReferenceSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testSourceReferencesUpsert(t *testing.T) {
	t.Parallel()

	if len(sourceReferenceAllColumns) == len(sourceReferencePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := SourceReference{}
	if err = randomize.Struct(seed, &o, sourceReferenceDBTypes, true); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SourceReference: %s", err)
	}

	count, err := SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, sourceReferenceDBTypes, false, sourceReferencePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize SourceReference struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert SourceReference: %s", err)
	}

	count, err = SourceReferences().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
