// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAccountUpdateQueueItem = "account_update_queue_item"

// AccountUpdateQueueItem mapped from table <account_update_queue_item>
type AccountUpdateQueueItem struct {
	Pubkey    string     `gorm:"column:pubkey;primaryKey" json:"pubkey" db:"pubkey"`
	ProgramID string     `gorm:"column:program_id;not null" json:"programId" db:"program_id"`
	Time      *time.Time `gorm:"column:time;not null;default:now()" json:"time" db:"time"`
	Priority  *int32     `gorm:"column:priority;not null;default:3" json:"priority" db:"priority"`
	Try       int32      `gorm:"column:try;not null" json:"try" db:"try"`
	MaxTry    *int32     `gorm:"column:max_try;not null;default:10" json:"maxTry" db:"max_try"`
	RetryTime *time.Time `gorm:"column:retry_time" json:"retryTime" db:"retry_time"`
}

// TableName AccountUpdateQueueItem's table name
func (*AccountUpdateQueueItem) TableName() string {
	return TableNameAccountUpdateQueueItem
}
