// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDepositMetric = "deposit_metric"

// DepositMetric mapped from table <deposit_metric>
type DepositMetric struct {
	Signature           string    `gorm:"column:signature;primaryKey" json:"signature" db:"signature"`
	IxIndex             int32     `gorm:"column:ix_index;primaryKey" json:"ixIndex" db:"ix_index"`
	IxName              string    `gorm:"column:ix_name;not null" json:"ixName" db:"ix_name"`
	IxVersion           int32     `gorm:"column:ix_version;not null" json:"ixVersion" db:"ix_version"`
	Slot                int32     `gorm:"column:slot;not null" json:"slot" db:"slot"`
	Time                time.Time `gorm:"column:time;not null" json:"time" db:"time"`
	Vault               string    `gorm:"column:vault;not null" json:"vault" db:"vault"`
	TokenAMint          string    `gorm:"column:token_a_mint;not null" json:"tokenAMint" db:"token_a_mint"`
	Referrer            *string   `gorm:"column:referrer" json:"referrer" db:"referrer"`
	TokenADepositAmount uint64    `gorm:"column:token_a_deposit_amount;not null" json:"tokenADepositAmount" db:"token_a_deposit_amount"`
	TokenAUsdPriceDay   *uint64   `gorm:"column:token_a_usd_price_day" json:"tokenAUsdPriceDay" db:"token_a_usd_price_day"`
}

// TableName DepositMetric's table name
func (*DepositMetric) TableName() string {
	return TableNameDepositMetric
}
