// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDripMetric = "drip_metric"

// DripMetric mapped from table <drip_metric>
type DripMetric struct {
	Signature                  string    `gorm:"column:signature;primaryKey" json:"signature" db:"signature"`
	IxIndex                    int32     `gorm:"column:ix_index;primaryKey" json:"ixIndex" db:"ix_index"`
	IxName                     string    `gorm:"column:ix_name;not null" json:"ixName" db:"ix_name"`
	IxVersion                  int32     `gorm:"column:ix_version;not null" json:"ixVersion" db:"ix_version"`
	Slot                       int32     `gorm:"column:slot;not null" json:"slot" db:"slot"`
	Time                       time.Time `gorm:"column:time;not null" json:"time" db:"time"`
	Vault                      string    `gorm:"column:vault;not null" json:"vault" db:"vault"`
	TokenAMint                 string    `gorm:"column:token_a_mint;not null" json:"tokenAMint" db:"token_a_mint"`
	TokenBMint                 string    `gorm:"column:token_b_mint;not null" json:"tokenBMint" db:"token_b_mint"`
	VaultTokenASwappedAmount   uint64    `gorm:"column:vault_token_a_swapped_amount;not null" json:"vaultTokenASwappedAmount" db:"vault_token_a_swapped_amount"`
	VaultTokenBReceivedAmount  uint64    `gorm:"column:vault_token_b_received_amount;not null" json:"vaultTokenBReceivedAmount" db:"vault_token_b_received_amount"`
	KeeperTokenAReceivedAmount uint64    `gorm:"column:keeper_token_a_received_amount;not null" json:"keeperTokenAReceivedAmount" db:"keeper_token_a_received_amount"`
	TokenAUsdPriceDay          *uint64   `gorm:"column:token_a_usd_price_day" json:"tokenAUsdPriceDay" db:"token_a_usd_price_day"`
	TokenBUsdPriceDay          *uint64   `gorm:"column:token_b_usd_price_day" json:"tokenBUsdPriceDay" db:"token_b_usd_price_day"`
}

// TableName DripMetric's table name
func (*DripMetric) TableName() string {
	return TableNameDripMetric
}
