// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTokenAccount = "token_account"

// TokenAccount mapped from table <token_account>
type TokenAccount struct {
	Pubkey string `gorm:"column:pubkey;type:varchar;primaryKey" json:"pubkey" db:"pubkey"`
	Mint   string `gorm:"column:mint;type:varchar;not null" json:"mint" db:"mint"`
	Owner  string `gorm:"column:owner;type:varchar;not null" json:"owner" db:"owner"`
	Amount uint64 `gorm:"column:amount;type:numeric;not null" json:"amount" db:"amount"`
	State  string `gorm:"column:state;type:varchar;not null" json:"state" db:"state"`
}

// TableName TokenAccount's table name
func (*TokenAccount) TableName() string {
	return TableNameTokenAccount
}
