// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "reflect"

const TableNameTransactionProcessingCheckpoint = "transaction_processing_checkpoint"

// TransactionProcessingCheckpoint mapped from table <transaction_processing_checkpoint>
type TransactionProcessingCheckpoint struct {
	ID        int32  `gorm:"column:id;primaryKey" json:"id" db:"id"`
	Signature string `gorm:"column:signature;not null" json:"signature" db:"signature"`
	Slot      uint64 `gorm:"column:slot;not null" json:"slot" db:"slot"`
}

// TableName TransactionProcessingCheckpoint's table name
func (*TransactionProcessingCheckpoint) TableName() string {
	return TableNameTransactionProcessingCheckpoint
}

func (t TransactionProcessingCheckpoint) GetAllColumns() []string {
	var res []string
	numFields := reflect.TypeOf(t).NumField()
	i := 0
	for i < numFields {
		field := reflect.TypeOf(t).Field(i)
		res = append(res, field.Tag.Get("db"))
		i++
	}
	return res
}
