// Code generated by https://github.com/gagliardetto/anchor-go. DO NOT EDIT.

package drip

import (
	"errors"
	ag_binary "github.com/gagliardetto/binary"
	ag_solanago "github.com/gagliardetto/solana-go"
	ag_format "github.com/gagliardetto/solana-go/text/format"
	ag_treeout "github.com/gagliardetto/treeout"
)

// WithdrawB is the `withdrawB` instruction.
type WithdrawB struct {

	// [0] = [] vault
	//
	// [1] = [] vaultProtoConfig
	//
	// [2] = [] vaultPeriodI
	//
	// [3] = [] vaultPeriodJ
	//
	// [4] = [WRITE] userPosition
	//
	// [5] = [] userPositionNftAccount
	//
	// [6] = [WRITE] vaultTokenBAccount
	//
	// [7] = [WRITE] userTokenBAccount
	//
	// [8] = [WRITE] vaultTreasuryTokenBAccount
	//
	// [9] = [] userPositionNftMint
	//
	// [10] = [] tokenBMint
	//
	// [11] = [SIGNER] withdrawer
	//
	// [12] = [] tokenProgram
	//
	// [13] = [] associatedTokenProgram
	ag_solanago.AccountMetaSlice `bin:"-"`
}

// NewWithdrawBInstructionBuilder creates a new `WithdrawB` instruction builder.
func NewWithdrawBInstructionBuilder() *WithdrawB {
	nd := &WithdrawB{
		AccountMetaSlice: make(ag_solanago.AccountMetaSlice, 14),
	}
	return nd
}

// SetVaultAccount sets the "vault" account.
func (inst *WithdrawB) SetVaultAccount(vault ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[0] = ag_solanago.Meta(vault)
	return inst
}

// GetVaultAccount gets the "vault" account.
func (inst *WithdrawB) GetVaultAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(0)
}

// SetVaultProtoConfigAccount sets the "vaultProtoConfig" account.
func (inst *WithdrawB) SetVaultProtoConfigAccount(vaultProtoConfig ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[1] = ag_solanago.Meta(vaultProtoConfig)
	return inst
}

// GetVaultProtoConfigAccount gets the "vaultProtoConfig" account.
func (inst *WithdrawB) GetVaultProtoConfigAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(1)
}

// SetVaultPeriodIAccount sets the "vaultPeriodI" account.
func (inst *WithdrawB) SetVaultPeriodIAccount(vaultPeriodI ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[2] = ag_solanago.Meta(vaultPeriodI)
	return inst
}

// GetVaultPeriodIAccount gets the "vaultPeriodI" account.
func (inst *WithdrawB) GetVaultPeriodIAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(2)
}

// SetVaultPeriodJAccount sets the "vaultPeriodJ" account.
func (inst *WithdrawB) SetVaultPeriodJAccount(vaultPeriodJ ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[3] = ag_solanago.Meta(vaultPeriodJ)
	return inst
}

// GetVaultPeriodJAccount gets the "vaultPeriodJ" account.
func (inst *WithdrawB) GetVaultPeriodJAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(3)
}

// SetUserPositionAccount sets the "userPosition" account.
func (inst *WithdrawB) SetUserPositionAccount(userPosition ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[4] = ag_solanago.Meta(userPosition).WRITE()
	return inst
}

// GetUserPositionAccount gets the "userPosition" account.
func (inst *WithdrawB) GetUserPositionAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(4)
}

// SetUserPositionNftAccountAccount sets the "userPositionNftAccount" account.
func (inst *WithdrawB) SetUserPositionNftAccountAccount(userPositionNftAccount ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[5] = ag_solanago.Meta(userPositionNftAccount)
	return inst
}

// GetUserPositionNftAccountAccount gets the "userPositionNftAccount" account.
func (inst *WithdrawB) GetUserPositionNftAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(5)
}

// SetVaultTokenBAccountAccount sets the "vaultTokenBAccount" account.
func (inst *WithdrawB) SetVaultTokenBAccountAccount(vaultTokenBAccount ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[6] = ag_solanago.Meta(vaultTokenBAccount).WRITE()
	return inst
}

// GetVaultTokenBAccountAccount gets the "vaultTokenBAccount" account.
func (inst *WithdrawB) GetVaultTokenBAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(6)
}

// SetUserTokenBAccountAccount sets the "userTokenBAccount" account.
func (inst *WithdrawB) SetUserTokenBAccountAccount(userTokenBAccount ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[7] = ag_solanago.Meta(userTokenBAccount).WRITE()
	return inst
}

// GetUserTokenBAccountAccount gets the "userTokenBAccount" account.
func (inst *WithdrawB) GetUserTokenBAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(7)
}

// SetVaultTreasuryTokenBAccountAccount sets the "vaultTreasuryTokenBAccount" account.
func (inst *WithdrawB) SetVaultTreasuryTokenBAccountAccount(vaultTreasuryTokenBAccount ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[8] = ag_solanago.Meta(vaultTreasuryTokenBAccount).WRITE()
	return inst
}

// GetVaultTreasuryTokenBAccountAccount gets the "vaultTreasuryTokenBAccount" account.
func (inst *WithdrawB) GetVaultTreasuryTokenBAccountAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(8)
}

// SetUserPositionNftMintAccount sets the "userPositionNftMint" account.
func (inst *WithdrawB) SetUserPositionNftMintAccount(userPositionNftMint ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[9] = ag_solanago.Meta(userPositionNftMint)
	return inst
}

// GetUserPositionNftMintAccount gets the "userPositionNftMint" account.
func (inst *WithdrawB) GetUserPositionNftMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(9)
}

// SetTokenBMintAccount sets the "tokenBMint" account.
func (inst *WithdrawB) SetTokenBMintAccount(tokenBMint ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[10] = ag_solanago.Meta(tokenBMint)
	return inst
}

// GetTokenBMintAccount gets the "tokenBMint" account.
func (inst *WithdrawB) GetTokenBMintAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(10)
}

// SetWithdrawerAccount sets the "withdrawer" account.
func (inst *WithdrawB) SetWithdrawerAccount(withdrawer ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[11] = ag_solanago.Meta(withdrawer).SIGNER()
	return inst
}

// GetWithdrawerAccount gets the "withdrawer" account.
func (inst *WithdrawB) GetWithdrawerAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(11)
}

// SetTokenProgramAccount sets the "tokenProgram" account.
func (inst *WithdrawB) SetTokenProgramAccount(tokenProgram ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[12] = ag_solanago.Meta(tokenProgram)
	return inst
}

// GetTokenProgramAccount gets the "tokenProgram" account.
func (inst *WithdrawB) GetTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(12)
}

// SetAssociatedTokenProgramAccount sets the "associatedTokenProgram" account.
func (inst *WithdrawB) SetAssociatedTokenProgramAccount(associatedTokenProgram ag_solanago.PublicKey) *WithdrawB {
	inst.AccountMetaSlice[13] = ag_solanago.Meta(associatedTokenProgram)
	return inst
}

// GetAssociatedTokenProgramAccount gets the "associatedTokenProgram" account.
func (inst *WithdrawB) GetAssociatedTokenProgramAccount() *ag_solanago.AccountMeta {
	return inst.AccountMetaSlice.Get(13)
}

func (inst WithdrawB) Build() *Instruction {
	return &Instruction{BaseVariant: ag_binary.BaseVariant{
		Impl:   inst,
		TypeID: Instruction_WithdrawB,
	}}
}

// ValidateAndBuild validates the instruction parameters and accounts;
// if there is a validation error, it returns the error.
// Otherwise, it builds and returns the instruction.
func (inst WithdrawB) ValidateAndBuild() (*Instruction, error) {
	if err := inst.Validate(); err != nil {
		return nil, err
	}
	return inst.Build(), nil
}

func (inst *WithdrawB) Validate() error {
	// Check whether all (required) accounts are set:
	{
		if inst.AccountMetaSlice[0] == nil {
			return errors.New("accounts.Vault is not set")
		}
		if inst.AccountMetaSlice[1] == nil {
			return errors.New("accounts.VaultProtoConfig is not set")
		}
		if inst.AccountMetaSlice[2] == nil {
			return errors.New("accounts.VaultPeriodI is not set")
		}
		if inst.AccountMetaSlice[3] == nil {
			return errors.New("accounts.VaultPeriodJ is not set")
		}
		if inst.AccountMetaSlice[4] == nil {
			return errors.New("accounts.UserPosition is not set")
		}
		if inst.AccountMetaSlice[5] == nil {
			return errors.New("accounts.UserPositionNftAccount is not set")
		}
		if inst.AccountMetaSlice[6] == nil {
			return errors.New("accounts.VaultTokenBAccount is not set")
		}
		if inst.AccountMetaSlice[7] == nil {
			return errors.New("accounts.UserTokenBAccount is not set")
		}
		if inst.AccountMetaSlice[8] == nil {
			return errors.New("accounts.VaultTreasuryTokenBAccount is not set")
		}
		if inst.AccountMetaSlice[9] == nil {
			return errors.New("accounts.UserPositionNftMint is not set")
		}
		if inst.AccountMetaSlice[10] == nil {
			return errors.New("accounts.TokenBMint is not set")
		}
		if inst.AccountMetaSlice[11] == nil {
			return errors.New("accounts.Withdrawer is not set")
		}
		if inst.AccountMetaSlice[12] == nil {
			return errors.New("accounts.TokenProgram is not set")
		}
		if inst.AccountMetaSlice[13] == nil {
			return errors.New("accounts.AssociatedTokenProgram is not set")
		}
	}
	return nil
}

func (inst *WithdrawB) EncodeToTree(parent ag_treeout.Branches) {
	parent.Child(ag_format.Program(ProgramName, ProgramID)).
		//
		ParentFunc(func(programBranch ag_treeout.Branches) {
			programBranch.Child(ag_format.Instruction("WithdrawB")).
				//
				ParentFunc(func(instructionBranch ag_treeout.Branches) {

					// Parameters of the instruction:
					instructionBranch.Child("Params[len=0]").ParentFunc(func(paramsBranch ag_treeout.Branches) {})

					// Accounts of the instruction:
					instructionBranch.Child("Accounts[len=14]").ParentFunc(func(accountsBranch ag_treeout.Branches) {
						accountsBranch.Child(ag_format.Meta("                 vault", inst.AccountMetaSlice.Get(0)))
						accountsBranch.Child(ag_format.Meta("      vaultProtoConfig", inst.AccountMetaSlice.Get(1)))
						accountsBranch.Child(ag_format.Meta("          vaultPeriodI", inst.AccountMetaSlice.Get(2)))
						accountsBranch.Child(ag_format.Meta("          vaultPeriodJ", inst.AccountMetaSlice.Get(3)))
						accountsBranch.Child(ag_format.Meta("          userPosition", inst.AccountMetaSlice.Get(4)))
						accountsBranch.Child(ag_format.Meta("       userPositionNft", inst.AccountMetaSlice.Get(5)))
						accountsBranch.Child(ag_format.Meta("           vaultTokenB", inst.AccountMetaSlice.Get(6)))
						accountsBranch.Child(ag_format.Meta("            userTokenB", inst.AccountMetaSlice.Get(7)))
						accountsBranch.Child(ag_format.Meta("   vaultTreasuryTokenB", inst.AccountMetaSlice.Get(8)))
						accountsBranch.Child(ag_format.Meta("   userPositionNftMint", inst.AccountMetaSlice.Get(9)))
						accountsBranch.Child(ag_format.Meta("            tokenBMint", inst.AccountMetaSlice.Get(10)))
						accountsBranch.Child(ag_format.Meta("            withdrawer", inst.AccountMetaSlice.Get(11)))
						accountsBranch.Child(ag_format.Meta("          tokenProgram", inst.AccountMetaSlice.Get(12)))
						accountsBranch.Child(ag_format.Meta("associatedTokenProgram", inst.AccountMetaSlice.Get(13)))
					})
				})
		})
}

func (obj WithdrawB) MarshalWithEncoder(encoder *ag_binary.Encoder) (err error) {
	return nil
}
func (obj *WithdrawB) UnmarshalWithDecoder(decoder *ag_binary.Decoder) (err error) {
	return nil
}

// NewWithdrawBInstruction declares a new WithdrawB instruction with the provided parameters and accounts.
func NewWithdrawBInstruction(
	// Accounts:
	vault ag_solanago.PublicKey,
	vaultProtoConfig ag_solanago.PublicKey,
	vaultPeriodI ag_solanago.PublicKey,
	vaultPeriodJ ag_solanago.PublicKey,
	userPosition ag_solanago.PublicKey,
	userPositionNftAccount ag_solanago.PublicKey,
	vaultTokenBAccount ag_solanago.PublicKey,
	userTokenBAccount ag_solanago.PublicKey,
	vaultTreasuryTokenBAccount ag_solanago.PublicKey,
	userPositionNftMint ag_solanago.PublicKey,
	tokenBMint ag_solanago.PublicKey,
	withdrawer ag_solanago.PublicKey,
	tokenProgram ag_solanago.PublicKey,
	associatedTokenProgram ag_solanago.PublicKey) *WithdrawB {
	return NewWithdrawBInstructionBuilder().
		SetVaultAccount(vault).
		SetVaultProtoConfigAccount(vaultProtoConfig).
		SetVaultPeriodIAccount(vaultPeriodI).
		SetVaultPeriodJAccount(vaultPeriodJ).
		SetUserPositionAccount(userPosition).
		SetUserPositionNftAccountAccount(userPositionNftAccount).
		SetVaultTokenBAccountAccount(vaultTokenBAccount).
		SetUserTokenBAccountAccount(userTokenBAccount).
		SetVaultTreasuryTokenBAccountAccount(vaultTreasuryTokenBAccount).
		SetUserPositionNftMintAccount(userPositionNftMint).
		SetTokenBMintAccount(tokenBMint).
		SetWithdrawerAccount(withdrawer).
		SetTokenProgramAccount(tokenProgram).
		SetAssociatedTokenProgramAccount(associatedTokenProgram)
}
