// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameTokenPair = "token_pair"

// TokenPair mapped from table <token_pair>
type TokenPair struct {
	ID     string `gorm:"column:id;type:uuid;primaryKey" json:"id" yaml:"id"`
	TokenA string `gorm:"column:token_a;type:varchar;not null" json:"tokenA" yaml:"tokenA"`
	TokenB string `gorm:"column:token_b;type:varchar;not null" json:"tokenB" yaml:"tokenB"`
}

// TableName TokenPair's table name
func (*TokenPair) TableName() string {
	return TableNameTokenPair
}
