oepnapi: "3.0.0"
info:
  title: Drip Backend
  description: Drip backend service.
  contact:
    email: dcafmocha@protonmail.com
    name: Dcaf Mocha
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

paths:
  /:
    get:
      summary: Health Check
      description: Ping server.
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pingResponse'

  /swagger.json:
    get:
      summary: Swagger spec
      produces:
        - application/json
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /vaults:
    get:
      summary: Get Supported Vaults
      description: Get all vaults with filters.
      consumes:
        - application/json
      parameters:
        - $ref: "#/components/parameters/tokenA"
        - $ref: "#/components/parameters/tokenB"
        - $ref: "#/components/parameters/granularity"
      produces:
        - application/json
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listVaultsResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /mint:
    post:
      summary: Mint tokens (DEVNET ONLY)
      description: mint test tokens to a desired associated token account, or passed
        in token account
      consumes:
        - application/json
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mintRequest'
      produces:
        - application/json
      tags:
        - mint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mintResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  parameters:
    tokenA:
      name: tokenA
      in: query
      schema:
        type: string
    tokenB:
      name: tokenB
      in: query
      schema:
        type: string
    granularity:
      name: granularity
      description: Granularity in seconds.
      in: query
      schema:
        type: number
  schemas:
    mintRequest:
      required:
        - mint
        - wallet
        - amount
      properties:
        mint:
          type: string
        wallet:
          type: string
        amount:
          type: string

    mintResponse:
      required:
        - txHash
      properties:
        txHash:
          type: string

    pingResponse:
      required:
        - message
      properties:
        message:
          type: string

    errorResponse:
      required:
        - error
      properties:
        error:
          type: string

    listVaultsResponse:
      type: array
      items:
        type: object
        required:
          - vault
          - vaultProtoConfig
          - vaultTokenAAcount
          - vaultTokenBAccount
          - vaultTreasuryTokenBAccount
          - tokenAMint
          - tokenASymbol
          - tokenBMint
          - tokenBSymbol
          - swapTokenMint
          - swapTokenAAccount
          - swapTokenBAccount
          - swapFeeAccount
          - swapAuthority
          - swap
        properties:
          vault:
            type: string
            example: 3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV
          vaultProtoConfig:
            type: string
            example: mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L
          vaultTokenAAcount:
            type: string
            exampe: 6PmcdLzbELLxaPc3Fq6FjiSj7wtjA4MEt1UCZBnHh6tw
          vaultTokenBAccount:
            type: string
            example: 5q7HLgfvxmkqAK6QaEFYrNmvKvzQZjWJzjwRu4toi9Sw
          vaultTreasuryTokenBAccount:
            type: string
            example: CrVdqMmYCbBs8zG2rmwdWgmsSArKTbMUv3qvTz8J6YWC
          tokenAMint:
            type: string
            example: BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq
          tokenASymbol:
            type: string
            example: SOL
          tokenBMint:
            type: string
            example: ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8
          tokenBSymbol:
            type: string
            example: USDC
          swapTokenMint:
            type: string
            example: 5U7X6mgvmsu5sSUFWCXtPhsNMVmEyZ4zJzhgweVTjFfX
          swapTokenAAccount:
            type: string
            example: 7cJ5h3JgGBYKt1QzD8z5veLvBQcaEuJMm9CyFp6c5XeG
          swapTokenBAccount:
            type: string
            example: 6fg6TGxUjBKF5BBtreMVpDP7YGrnrizHsDaME1UE5ejy
          swapFeeAccount:
            type: string
            example: Gj8DqPPVjgZwTjvvQA7gRzFE22fT3s9ztAYfiTim4HiH
          swapAuthority:
            type: string
            example: 216G8d1QWwLmxw89Y5Kai69nE1MTzMPNMArX2mQ7KK2Z
          swap:
            type: string
            example: 8Vx5D6dKfv1vyLzL6hdxB1KNnRr5yiHSaw8bDh5LVNAE
