definitions:
  api.MintResponse:
    properties:
      Error:
        type: string
      txHash:
        type: string
    type: object
  api.PingResponse:
    properties:
      message:
        example: pong
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: dcafmocha@protonmail.com
    name: Dcaf Mocha
  description: Drip backend service.
  title: Drip Backend
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PingResponse'
      summary: Health Check
      tags:
      - info
  /mint:
    get:
      consumes:
      - application/json
      description: mint test tokens to a desired associated token account, or passed
        in token account
      parameters:
      - description: Mint base58 pubkey.
        in: query
        name: mint
        required: true
        type: string
      - description: Amount to be minted in base amount.
        in: query
        name: amount
        required: true
        type: string
      - description: Destination wallet. If specificed, the associated token account
          will be used. If it does not exist, one will be created. One of destinationAccount
          or destinationWallet MUST be specified.
        in: query
        name: destinationWallet
        type: string
      - description: Destination token account. Must be initialized prior to calling.
          One of destinationAccount or destinationWallet MUST be specified.
        in: query
        name: destinationAccount
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.MintResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.MintResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.MintResponse'
      summary: Mint tokens (DEVNET ONLY)
      tags:
      - mint
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.PingResponse'
      summary: Health Check
      tags:
      - info
swagger: "2.0"
