oepnapi: "3.0.0"
info:
  title: Drip Backend
  description: Drip backend service.
  contact:
    email: dcafmocha@protonmail.com
    name: Dcaf Mocha
  version: 1.0.0
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http

paths:
  /:
    get:
      summary: Health Check
      description: Ping server.
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pingResponse'

  /swagger.json:
    get:
      summary: Swagger spec
      produces:
        - application/json
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
  /vaults:
    get:
      summary: Get Supported Vaults
      description: Get all vaults with filters.
      consumes:
        - application/json
      parameters:
        - $ref: "#/components/parameters/tokenA"
        - $ref: "#/components/parameters/tokenB"
        - $ref: "#/components/parameters/protoConfig"
      produces:
        - application/json
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listVaults'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
  /mint:
    post:
      summary: Mint tokens (DEVNET ONLY)
      description: mint test tokens to a desired associated token account, or passed
        in token account
      consumes:
        - application/json
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mintRequest'
      produces:
        - application/json
      tags:
        - mint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mintResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
components:
  parameters:
    tokenA:
      name: tokenA
      in: query
      schema:
        type: string
    tokenB:
      name: tokenB
      in: query
      schema:
        type: string
    protoConfig:
      name: protoConfig
      description: Vault proto config public key.
      in: query
      schema:
        type: string
  schemas:
    mintRequest:
      required:
        - mint
        - wallet
        - amount
      properties:
        mint:
          type: string
        wallet:
          type: string
        amount:
          type: string

    mintResponse:
      required:
        - txHash
      properties:
        txHash:
          type: string

    pingResponse:
      required:
        - message
      properties:
        message:
          type: string

    errorResponse:
      required:
        - error
      properties:
        error:
          type: string

    listVaults:
      type: array
      items:
        type: object
        required:
          - pubkey
          - protoConfig
          - tokenAMint
          - tokenBMint
          - tokenAAccount
          - tokenBAccount
          - treasuryTokenBAccount
          - lastDcaPeriod
          - dripAmount
          - dcaActivationTimestamp
        properties:
          pubkey:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          protoConfig:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          tokenAAccount:
            type: string
            exampe: "6PmcdLzbELLxaPc3Fq6FjiSj7wtjA4MEt1UCZBnHh6tw"
          tokenBAccount:
            type: string
            example: "5q7HLgfvxmkqAK6QaEFYrNmvKvzQZjWJzjwRu4toi9Sw"
          treasuryTokenBAccount:
            type: string
            example: "CrVdqMmYCbBs8zG2rmwdWgmsSArKTbMUv3qvTz8J6YWC"
          tokenAMint:
            type: string
            example: "BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq"
          tokenBMint:
            type: string
            example: "ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8"
          lastDcaPeriod:
            type: string
            example: "123"
          dripAmount:
            type: string
            example: "123"
          dcaActivationTimestamp:
            type: string
            example: "1652747980"
            description: unix timestamp
