openapi: 3.0.0
info:
  title: Drip Backend
  description: Drip backend service.
  contact:
    email: dcafmocha@protonmail.com
    name: Dcaf Mocha
  version: 1.0.0

paths:
  /:
    get:
      summary: Health Check
      description: Ping api.
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/pingResponse'

  /swagger.json:
    get:
      summary: Swagger spec
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object

  /vaults:
    get:
      summary: Get Supported Vaults
      description: Get all vaults with filters.
      parameters:
        - $ref: "#/components/parameters/tokenA"
        - $ref: "#/components/parameters/tokenB"
        - $ref: "#/components/parameters/protoConfig"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listVaults'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /protoconfigs:
    get:
      summary: Get Proto Configs
      description: Get all proto configs with filters.
      parameters:
        - $ref: "#/components/parameters/tokenA"
        - $ref: "#/components/parameters/tokenB"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listProtoConfigs'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /vaultperiods:
    get:
      summary: Get Vault Periods
      description: Get vault periods with pagination and filters.
      parameters:
        - $ref: "#/components/parameters/requiredVault"
        - $ref: "#/components/parameters/vaultPeriod"
        - $ref: "#/components/parameters/offset"
        - $ref: "#/components/parameters/limit"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listVaultPeriods'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /swaps:
    get:
      summary: Get Token Swaps
      description: Get token swaps with filters.
      parameters:
        - $ref: "#/components/parameters/tokenPair"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listTokenSwaps'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /tokenpairs:
    get:
      summary: Get Token Pairs
      description: Get token pairs with filters.
      parameters:
        - $ref: "#/components/parameters/tokenA"
        - $ref: "#/components/parameters/tokenB"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listTokenPairs'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /tokens:
    get:
      summary: Get Tokens
      description: Get tokens with filters.
      parameters:
        - $ref: "#/components/parameters/tokenA"
        - $ref: "#/components/parameters/tokenB"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listTokens'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /positions:
    get:
      summary: Get User Positions
      description: Get all user positions.
      parameters:
        - $ref: "#/components/parameters/requiredWallet"
      tags:
        - info
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/listPositions'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

  /mint:
    post:
      summary: Mint tokens (DEVNET ONLY)
      description: mint test tokens to a desired associated token account, or passed
        in token account
      requestBody:
        description: Pet to add to the store
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/mintRequest'
      tags:
        - mint
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mintResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorResponse'

components:
  parameters:
    vault:
      name: vault
      in: query
      schema:
        type: string
    requiredVault:
      name: vault
      in: query
      schema:
        type: string
      required: true
    requiredWallet:
      name: Wallet
      in: query
      schema:
        type: string
      required: true
    vaultPeriod:
      name: vaultPeriod
      in: query
      schema:
        type: string
    tokenA:
      name: tokenA
      in: query
      schema:
        type: string
    tokenB:
      name: tokenB
      in: query
      schema:
        type: string
    tokenPair:
      name: tokenPair
      in: query
      schema:
        type: string
        description: Token pair identifier.
    protoConfig:
      name: protoConfig
      description: Vault proto config public key.
      in: query
      schema:
        type: string
    offset:
      name: offset
      in: query
      schema:
        type: integer
    limit:
      name: limit
      in: query
      schema:
        type: integer
  schemas:
    mintRequest:
      required:
        - mint
        - wallet
        - amount
      properties:
        mint:
          type: string
        wallet:
          type: string
        amount:
          type: string

    mintResponse:
      required:
        - txHash
      properties:
        txHash:
          type: string

    pingResponse:
      required:
        - message
      properties:
        message:
          type: string

    errorResponse:
      required:
        - error
      properties:
        error:
          type: string

    listVaults:
      type: array
      items:
        type: object
        required:
          - pubkey
          - protoConfig
          - tokenAMint
          - tokenBMint
          - tokenAAccount
          - tokenBAccount
          - treasuryTokenBAccount
          - lastDcaPeriod
          - dripAmount
          - dcaActivationTimestamp
        properties:
          pubkey:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          protoConfig:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          tokenAAccount:
            type: string
            example: "6PmcdLzbELLxaPc3Fq6FjiSj7wtjA4MEt1UCZBnHh6tw"
          tokenBAccount:
            type: string
            example: "5q7HLgfvxmkqAK6QaEFYrNmvKvzQZjWJzjwRu4toi9Sw"
          treasuryTokenBAccount:
            type: string
            example: "CrVdqMmYCbBs8zG2rmwdWgmsSArKTbMUv3qvTz8J6YWC"
          tokenAMint:
            type: string
            example: "BfqATYbPZJFdEdYWkEbFRBnhv1LB6wtLn299HjMmE4uq"
          tokenBMint:
            type: string
            example: "ASuqwxvC4FXxJGT9XqZMXbCKDQBaRTApEhN2oN3VL3A8"
          lastDcaPeriod:
            type: string
            example: "123"
          dripAmount:
            type: string
            example: "123"
          dcaActivationTimestamp:
            type: string
            example: "1652747980"
            description: unix timestamp

    listProtoConfigs:
      type: array
      items:
        type: object
        required:
          - pubkey
          - granularity
          - triggerDcaSpread
          - baseWithdrawalSpread
        properties:
          pubkey:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          granularity:
            type: integer
            example: 60
          triggerDcaSpread:
            type: integer
            example: 50
          baseWithdrawalSpread:
            type: integer
            example: 50

    listVaultPeriods:
      type: array
      items:
        type: object
        required:
          - pubkey
          - vault
          - periodId
          - twap
          - dar
        properties:
          pubkey:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          vault:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          periodId:
            type: string
            example: "123"
          twap:
            type: string
            example: "123"
          dar:
            type: string
            example: "123"

    listTokenPairs:
      type: array
      items:
        type: object
        required:
          - id
          - tokenA
          - tokenB
        properties:
          id:
            type: string
            example: "96b8b0ed-79a9-4972-bf5e-4ac8ab9e7fda"
          tokenA:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          tokenB:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
    
    listTokenSwaps:
      type: array
      items:
        type: object
        required:
          - pubkey
          - mint
          - authority
          - feeAccount
          - tokenAAccount
          - tokenBAccount
          - pair
        properties:
          pubkey:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          mint:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          authority:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          feeAccount:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          tokenAAccount:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          tokenBAccount:
            type: string
            example: "3iz6nZVjiGZtdEffAUDrVh4A5BnwN6ZoHj3nPPZtKJfV"
          pair:
            type: string
            example: "123"
            description: token pair reference identifier

    listTokens:
      type: array
      items:
        type: object
        required:
          - pubkey
          - symbol
          - decimals
          - iconUrl
        properties:
          pubkey:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          symbol:
            type: string
            example: "SOL"
          decimals:
            type: integer
            example: 10

    listPositions:
      type: array
      items:
        type: object
        required:
          - pubkey
          - vault
          - authority
          - depositedTokenAAmount
          - withdrawnTokenBAmount
          - depositTimestamp
          - dcaPeriodIdBeforeDeposit
          - numberOfSwaps
          - periodicDripAmount
          - isClosed
        properties:
          pubkey:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          vault:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          authority:
            type: string
            example: "mRcJ27ztTCFntbUvv7V2PSxqL9fJfg1KH4fzZSYVP4L"
          depositedTokenAAmount:
            type: integer
            example: 10000
          withdrawnTokenBAmount:
            type: integer
            example: 10000
          depositTimestamp:
            type: string
            example: "1652747980"
          dcaPeriodIdBeforeDeposit:
            type: integer
            example: 10
          numberOfSwaps:
            type: integer
            example: 543
          periodicDripAmount:
            type: integer
            example: 40
          isClosed:
            type: boolean