name: Build, Test
on:
  pull_request:
  push: { branches: main }

jobs:
  build_backend:
    name: Build Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Build
        run: go build main.go

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.1

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          only-new-issues: true
          skip-go-installation: true

