name: Deploy
on:
  push:
    branches:
      - prod
jobs:
  deploy_devnet:
    name: Deploy to Devnet Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - uses: akhileshns/heroku-deploy@v3.12.12 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "drip-backend-mainnet"
          heroku_email: "dcafmocha@protonmail.com"